# -*- coding: utf-8 -*-
"""gig-worker-credit-scoring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfUbh-rbTanFzkiy21VuZbv9cRPWYQbE
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/gig_worker_credit_dataset.csv")
df.head()

df.info()

df.shape

df.isnull().sum()

print("Rows, Columns:", df.shape)

df["credit_risk_category"].value_counts()

df["credit_risk_category"].value_counts(normalize=True)*100

df.dtypes

df["worker_id"].head()

df = df.drop("worker_id", axis=1)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
categorical_cols = ["gender","city_tier","gig_platform","account_balance_trend","previous_microloan_taken","previous_microloan_repaid","credit_risk_category"]
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

df.head()

X = df.drop("credit_risk_category",axis=1)
y = df["credit_risk_category"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_lr = accuracy_score(y_test,y_pred_lr)
print("Logistic Regression Accuracy:",accuracy_lr)

from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred_lr ))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_lr)
print(cm)

results = {}
results["Logistic Regression"] = accuracy_lr

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100,random_state=42)
rf.fit(X_train,y_train)
print("Model trained")
y_pred_rf = rf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_rf = accuracy_score(y_test,y_pred_rf)
print("Random Forest Accuracy:",accuracy_rf)

print(classification_report(y_test,y_pred_rf))

results["Random Forest"] = accuracy_rf

from xgboost import XGBClassifier
xgb = XGBClassifier(random_state=42,eval_metric="mlogloss")
xgb.fit(X_train,y_train)
y_pred_xgb = xgb.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_xgb = accuracy_score(y_test,y_pred_xgb)
print("XGBoost Accuracy:",accuracy_xgb)

results = {
    "Logistic Regression": accuracy_lr,
    "Random Forest": accuracy_rf,
    "XGBoost": accuracy_xgb
}

print(results)